language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
  include:
    - php: 5.5
      env: ES_VERSION=2.3.3 SYMFONY_VERSION='3.*'
    - php: 5.6
      env: ES_VERSION=2.3.3 SYMFONY_VERSION='3.*'
    - php: 7.0
      env: ES_VERSION=2.3.3 SYMFONY_VERSION='3.*'
    - php: 7.1
      env: ES_VERSION=2.3.3 SYMFONY_VERSION='3.*'
    - php: hhvm
      env: ES_VERSION=2.3.3 SYMFONY_VERSION='3.*'
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-lowest --prefer-stable" ES_VERSION=2.3.3 SYMFONY_VERSION='3.*'
    - php: 5.6
      env: SYMFONY_VERSION='2.8.*' ES_VERSION=2.3.3
    - php: 7.1
      env: SYMFONY_VERSION='2.8.*' ES_VERSION=2.3.3
  allow_failures:
    - php: hhvm
  fast_finish: true

install:
  - composer self-update
  - mkdir /tmp/elasticsearch
  - wget -O - https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - /tmp/elasticsearch/bin/plugin install -b mapper-attachments
  - /tmp/elasticsearch/bin/elasticsearch --daemonize --path.data /tmp
  - .travis/wait-for-elasticsearch.sh

before_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add travis.php.ini; fi;
  - if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then composer require --dev --no-update doctrine/mongodb-odm=^1; fi;
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - if [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi;
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - composer update $COMPOSER_FLAGS --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
