language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

env:
  global:
    - PHPUNIT_FLAGS="-v"
    - ES_VERSION="5.2.1"

matrix:
  fast_finish: true
  include:
    # Minimum supported dependencies with min and max PHP version
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

    # Latest supported dependencies with each PHP version
    - php: 7.1
    - php: 7.2
    - php: 7.3
      env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-clover=coverage.clover"

    # Install all SF components in the same major version, see https://github.com/dunglas/symfony-lock
    - php: 7.3
      env: SYMFONY_VERSION="^4"

    - php: 7.3
      env: SYMFONY_VERSION="^5"

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi

install:
  # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
  - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update dunglas/symfony-lock=$SYMFONY_VERSION; fi;
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
  - mkdir /tmp/elasticsearch
  - wget -O - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - /tmp/elasticsearch/bin/elasticsearch-plugin install -b mapper-attachments
  - /tmp/elasticsearch/bin/elasticsearch --daemonize -Epath.data=/tmp
  - .travis/wait-for-elasticsearch.sh

before_script:
  - phpenv config-add .travis/php.ini
  - if [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;

script:
  - vendor/bin/phpunit ${PHPUNIT_FLAGS}

after_script:
  - if [[ $COVERAGE = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $COVERAGE = true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

